### ISSUE TITLE
Service fail to start-up

### ISSUE THREAD

**Issue by ltronky** [sharelatex/track-changes-sharelatex#14]
Recently I the track-changes service crashes at boot due to a NPE from the settings file.
The problem seems to be introduced with the https://github.com/sharelatex/track-changes-sharelatex/commit/d09dd2bff74f8e192df211b0de5449c202ad3bea commit, where the 'filestore' key is changed to 'trackchanges' in MongoAWS.coffee, but not in the config file.

**Comment by briangough** [comment]
Thanks for the bug report,  I've just made a commit to remove the dependency on s3 settings at startup (https://github.com/sharelatex/track-changes-sharelatex/commit/bd9c4d50d1e5a907712ab22f1025275b5c0b3f73).
