### ISSUE TITLE
[Support] - Trackchanges within the latest docker image does not work

### ISSUE THREAD

**Issue by bott0r** [sharelatex/track-changes-sharelatex#39]
track changes and comments do not work on dockerimage v 0.6.2 or latest.

**Comment by ShaneKilkelly** [comment]
Hi there,

Just to clarify, are you using Server Pro, or the [Community Edition](https://hub.docker.com/r/sharelatex/sharelatex/) image?

Currently, Track Changes is only available in the Server Pro image.

**Comment by bott0r** [comment]
That is good to know!
